repos:
  - hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - args:
          - --allow-missing-credentials
        id: detect-aws-credentials
    repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.0.1
  - hooks:
      - args: ["--profile", "black", "--filter-files"]
        id: isort
    repo: git@github.com:pycqa/isort.git
    rev: 5.8.0
  - hooks:
      - id: black
    repo: git@github.com:psf/black.git
    rev: 21.5b2
  - hooks:
      - additional_dependencies: []
        id: shellcheck
    repo: git@github.com:jumanjihouse/pre-commit-hooks.git
    rev: 2.1.5
