import typing as t

def encrypt_bytes(unencrypted_data: bytes, password: t.Union[bytes, str]) -> bytes: ...
def decrypt_bytes(encrypted_data: bytes, password: t.Union[bytes, str]) -> bytes: ...
def generate_salt(size: int = ...) -> bytes: ...
def generate_key(
    password: str, salt: t.Optional[bytes] = ..., key_length: t.Optional[int] = ...
) -> t.Tuple[bytes, bytes]: ...
