import pathlib
import typing as t

def create_backup(path: pathlib.Path, suffix: str = ...) -> pathlib.Path: ...
def get_recursive_file_list(
    locations: t.Iterable[t.Union[str, pathlib.Path]]
) -> t.Iterator[pathlib.Path]: ...
def get_file_sha256_hash(file_path: pathlib.Path) -> str: ...
def get_terminal_size(
    fallback: t.Optional[t.Tuple[int, int]] = ...
) -> t.Tuple[int, int]: ...
