import typing as t

def common_backup_file(exists: bool = ...) -> t.Callable: ...
def common_password(
    confirmation_prompt: bool = ..., prompt_required: bool = ..., required: bool = ...
) -> t.Callable: ...
